# Coin Flips and Die Rolls

Simulating coin flips and die rolls to compute proportions for the following outcomes:
1. Two fair coin flips produce exactly two heads
2. Three fair coin flips produce exactly one head
3. Three biased coin flips with P(H) = 0.6 produce exactly one head
4. A die rolls an even number
5. Two dice roll a double

When simulating coin flips, use 0 to represent heads and 1 to represent tails.

When simulating die rolls, use the correct integers to match the numbers on the sides of a standard 6 sided die.

In [1]:
# import numpy
import numpy as np

### 1. Two fair coin flips produce exactly two heads

In [9]:
# Simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size = (int(1e6), 2))
tests

array([[0, 0],
       [0, 1],
       [1, 1],
       ...,
       [1, 0],
       [1, 1],
       [0, 1]])

In [7]:
# Sum of all tests
test_sums = tests.sum(axis = 1)
test_sums

array([1, 2, 1, ..., 2, 1, 0])

In [11]:
# Proportion of tests that produced exactly two heads
(test_sums == 0).mean()

0.249795

### 2. Three fair coin flips produce exactly one head

In [13]:
# simulate 1 million tests of three fair coin flips
tests = np.random.randint(2, size = (int(1e6), 3))
tests

array([[1, 1, 0],
       [1, 0, 1],
       [0, 1, 0],
       ...,
       [0, 0, 1],
       [1, 1, 0],
       [1, 0, 0]])

In [20]:
# sums of all tests
test_sums = tests.sum(axis = 1)
test_sums

array([2, 2, 1, ..., 1, 2, 1])

In [21]:
# proportion of tests that produced exactly one head
(test_sums == 2).mean()

0.37535

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [26]:
# simulate 1 million tests of three biased coin flips
# hint: use np.random.choice()
tests = np.random.choice([0, 1], size = (int(1e6), 3), p = [0.6, 0.4])
tests

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [1, 1, 0],
       [0, 0, 1]])

In [28]:
# sums of all tests
test_sums = tests.sum(axis = 1)
test_sums

array([1, 1, 0, ..., 0, 2, 1])

In [29]:
# proportion of tests that produced exactly one head
(test_sums == 2).mean()

0.287897

### 4. A die rolls an even number

In [40]:
tests = np.random.choice(np.arange(1, 7), size = int(1e6))
tests

array([4, 1, 6, ..., 1, 5, 2])

In [41]:
# proportion of tests that produced an even number
(tests % 2 == 0).mean()

0.499285

### 5. Two dice roll a double

In [42]:
# simulate the first million die rolls
first = np.random.choice(np.arange(6), size = int(1e6))

# simulate the second million die rolls
second = np.random.choice(np.arange(6), size = int(1e6))

# proportion of tests where the 1st and 2nd die rolled the same number
(first == second).mean()

0.166346